### ISSUE TITLE
How about running on a Windows PC?

### ISSUE THREAD

**Issue by Pythonpa** [saifhassan/Wav2Lip-HD#1]
If running on Windows, do I need any other configuration?

**Comment by saifhassan** [comment]
> If running on Windows, do I need any other configuration?

I don't think so, you will need any other configuration other than installations. Just set an environment and go with it.

**Comment by AIhasArrived** [comment]
@saifhassan  but the run_final.sh cannot work on windows can it? What can I do to run it on windows?
How did you do @Pythonpa ??
