### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by KelvinT9696** [saifhassan/Wav2Lip-HD#11]
raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Frames extracted and stored at  frames_wav2lip/najib
C:\Users\Kelvi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "inference_realesrgan.py", line 8, in <module>
    from realesrgan import RealESRGANer
  File "C:\Users\Kelvi\Wav2Lip-HD\Real-ESRGAN\realesrgan\__init__.py", line 6, in <module>
    from .version import *
ModuleNotFoundError: No module named 'realesrgan.version'
can anyone tell me how to solve this problem?

**Comment by saifhassan** [comment]
This line just to show version.
Go to `line 6` in `realesrgan_init_.py` and comment that line. It'll work.

**Comment by HaseebUllahAbbasi** [comment]
@KelvinT9696  it good to ask help but don't just put the whole logging , try to follow the standard of github issues, Thanks Happy Coding
