### ISSUE TITLE
Resolving numba and llvmlite issue

### ISSUE THREAD

**Issue by Ajit-WingsBI** [saifhassan/Wav2Lip-HD#12]
I am using this repo on windows  11 and using python 3.10.10 but still getting below issue

  │ exit code: 1
  ╰─> [24 lines of output]
      running bdist_wheel
      C:\GAN\Wav2Lip-HD\wav2lipenv\Scripts\python.exe C:\Users\vm\AppData\Local\Temp\pip-install-fqacuixn\llvmlite_cb3229fc34184465b2f139882de77573\ffi\build.py
      Trying generator 'Visual Studio 14 2015 Win64'
      Traceback (most recent call last):
        File "C:\Users\vm\AppData\Local\Temp\pip-install-fqacuixn\llvmlite_cb3229fc34184465b2f139882de77573\ffi\build.py", line 168, in <module>
          main()
        File "C:\Users\vm\AppData\Local\Temp\pip-install-fqacuixn\llvmlite_cb3229fc34184465b2f139882de77573\ffi\build.py", line 156, in main
          main_win32()
        File "C:\Users\vm\AppData\Local\Temp\pip-install-fqacuixn\llvmlite_cb3229fc34184465b2f139882de77573\ffi\build.py", line 88, in main_win32
          generator = find_win32_generator()
        File "C:\Users\vm\AppData\Local\Temp\pip-install-fqacuixn\llvmlite_cb3229fc34184465b2f139882de77573\ffi\build.py", line 76, in find_win32_generator 
          try_cmake(cmake_dir, build_dir, generator)
        File "C:\Users\vm\AppData\Local\Temp\pip-install-fqacuixn\llvmlite_cb3229fc34184465b2f139882de77573\ffi\build.py", line 28, in try_cmake
          subprocess.check_call(['cmake', '-G', generator, cmake_dir])
        File "C:\Users\vm\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 364, in check_call
          retcode = call(*popenargs, **kwargs)
        File "C:\Users\vm\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 345, in call
          with Popen(*popenargs, **kwargs) as p:
        File "C:\Users\vm\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\vm\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      error: command 'C:\\GAN\\Wav2Lip-HD\\wav2lipenv\\Scripts\\python.exe' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llvmlite
Failed to build numba llvmlite
ERROR: Could not build wheels for numba, llvmlite, which is required to install pyproject.toml-based projects

**Comment by saifhassan** [comment]
ins

> I am using this repo on windows 11 and using python 3.10.10 but still getting below issue
> 
> │ exit code: 1 ╰─> [24 lines of output] running bdist_wheel C:\GAN\Wav2Lip-HD\wav2lipenv\Scripts\python.exe C:\Users\vm\AppData\Local\Temp\pip-install-fqacuixn\llvmlite_cb3229fc34184465b2f139882de77573\ffi\build.py Trying generator 'Visual Studio 14 2015 Win64' Traceback (most recent call last): File "C:\Users\vm\AppData\Local\Temp\pip-install-fqacuixn\llvmlite_cb3229fc34184465b2f139882de77573\ffi\build.py", line 168, in main() File "C:\Users\vm\AppData\Local\Temp\pip-install-fqacuixn\llvmlite_cb3229fc34184465b2f139882de77573\ffi\build.py", line 156, in main main_win32() File "C:\Users\vm\AppData\Local\Temp\pip-install-fqacuixn\llvmlite_cb3229fc34184465b2f139882de77573\ffi\build.py", line 88, in main_win32 generator = find_win32_generator() File "C:\Users\vm\AppData\Local\Temp\pip-install-fqacuixn\llvmlite_cb3229fc34184465b2f139882de77573\ffi\build.py", line 76, in find_win32_generator try_cmake(cmake_dir, build_dir, generator) File "C:\Users\vm\AppData\Local\Temp\pip-install-fqacuixn\llvmlite_cb3229fc34184465b2f139882de77573\ffi\build.py", line 28, in try_cmake subprocess.check_call(['cmake', '-G', generator, cmake_dir]) File "C:\Users\vm\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 364, in check_call retcode = call(*popenargs, **kwargs) File "C:\Users\vm\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 345, in call with Popen(*popenargs, **kwargs) as p: File "C:\Users\vm\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Users\vm\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] The system cannot find the file specified error: command 'C:\GAN\Wav2Lip-HD\wav2lipenv\Scripts\python.exe' failed with exit code 1 [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for llvmlite Failed to build numba llvmlite ERROR: Could not build wheels for numba, llvmlite, which is required to install pyproject.toml-based projects

installation issues, try resolving, following links may be helpful:
https://stackoverflow.com/questions/65798319/llvmlite-failed-to-install-error-building-llvmlite
https://github.com/numba/llvmlite/issues/625

**Comment by AIhasArrived** [comment]
I wasnt able to fix it even with the link, not sure what to do

**Comment by AIhasArrived** [comment]
I removed torch and stuff from requriements, then installed reqs, then installed latest pytorch fresh (not sure if this was done here or retalker but its the same idea always, check versions of different libraries )
