### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by caoge4** [saifhassan/Wav2Lip-HD#17]
Could you add a MIT license for the repo for commercial use? Thx~

**Comment by saifhassan** [comment]
> Could you add a MIT license for the repo for commercial use? Thx~

updated.

**Comment by caoge4** [comment]
Thanks for your kind reply. 
Could you also add license assignment for the models ? e.g. add "model is licensed under MIT" in the Testing Model part 
Thx～
