### ISSUE TITLE
Where is inference_realesrgan.py?

### ISSUE THREAD

**Issue by Good0007** [saifhassan/Wav2Lip-HD#25]
[libx264 @ 0x1303e80] kb/s:370.54
Frames extracted and stored at  frames_wav2lip/mona
python: can't open file 'inference_realesrgan.py': [Errno 2] No such file or directory

**Comment by saifhassan** [comment]
> [libx264 @ 0x1303e80] kb/s:370.54
> Frames extracted and stored at frames_wav2lip/mona
> python: can't open file 'inference_realesrgan.py': [Errno 2] No such file or directory

You can find that file within sub-module (REAL-ESRGAN) Repo, clone it within main repository from this [Link](https://github.com/xinntao/Real-ESRGAN) and you can find ['inference_realsrgan.py'](https://github.com/xinntao/Real-ESRGAN/blob/master/inference_realesrgan.py) within REAL-ESRGAN repo

**Comment by AIhasArrived** [comment]
Yeah got same error, why did it copy while cloning the repo:
`\inference_realesrgan.py': [Errno 2] No such file or directory
`
![image](https://github.com/saifhassan/Wav2Lip-HD/assets/148225825/c7a138f7-a47a-409c-ae21-e9f31fc86bdc)
