### ISSUE TITLE
python: can't open file 'inference_realesrgan.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Woods30** [saifhassan/Wav2Lip-HD#3]

**Comment by saifhassan** [comment]
> No description provided.

clone [Real-ESRGAN](https://github.com/xinntao/Real-ESRGAN) repository within Wav2Lip-HD and then within Real-ESRGAN, you can find this file.

**Comment by Woods30** [comment]
thanks a lot! 👍

**Comment by AIhasArrived** [comment]
@saifhassan  I did that and i got this error:
```
from basicsr.archs.rrdbnet_arch import RRDBNet
ModuleNotFoundError: No module named 'basicsr'
```

my folder:
![image](https://github.com/saifhassan/Wav2Lip-HD/assets/148225825/7dd484c8-8f07-4f41-bce5-d3f63b7e4458)

**Comment by mitalpatel-investing** [comment]
Any luck on this?

**Comment by enguefto** [comment]
> @saifhassan I did that and i got this error:
> 
> ```
> from basicsr.archs.rrdbnet_arch import RRDBNet
> ModuleNotFoundError: No module named 'basicsr'
> ```
> 
> my folder: ![image](https://private-user-images.githubusercontent.com/148225825/281677452-7dd484c8-8f07-4f41-bce5-d3f63b7e4458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODAyOTIsIm5iZiI6MTczMjE3OTk5MiwicGF0aCI6Ii8xNDgyMjU4MjUvMjgxNjc3NDUyLTdkZDQ4NGM4LThmMDctNGY0MS1iY2U1LWQzZjYzYjdlNDQ1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQwOTA2MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDVlNGI4YTZlZTc5NDlkODFkYmU2OTJhYTZiYTE2NDA5YzE1YzkwNGM0YzhkMWQ3NjZkZGUzOTVmNWI2YTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SJem7Ql78uVibAldPetE7wnW4lvRcMCtanK0J36yvR8)

pip install basicsr
