### ISSUE TITLE
kennedy_hd.mp4 lips not synced with audio

### ISSUE THREAD

**Issue by FandyTADA** [saifhassan/Wav2Lip-HD#39]
i tried to generate HD version of my video but the sound is not synced with the lips.  I checked kennedy_hd.mp4 from github example video,  and also notice the out of sync sound and lips. 

Any advice?

**Comment by gotamafandy** [comment]
i've found the issue, just play with -r when generating video using ffmpeg, i changed the value -r 30, and its working
