### ISSUE TITLE
Inference is not working

### ISSUE THREAD

**Issue by himsfx** [saifhassan/Wav2Lip-HD#45]
File "inference.py", line 359, in <module>
main()
File "inference.py" line 245, in main
raise ValueError(--face argument must be a valid path to video/image file')
ValueError: --face argument must be a valid path to video/image file

**Comment by vishal24102002** [comment]
check your video or image path that you used in the command & if it is wrong try using correcting it

**Comment by himsfx** [comment]
Hi... Thanks a ton for your reply and quick attention to this matter. The issue has been resolved now.

**Comment by vishal24102002** [comment]
ok does your output video contains a bounded box around its face

**Comment by himsfx** [comment]
No Vishal my output video does not have a bounding box around the face.

**Comment by vishal24102002** [comment]
Uploading VID-20241015-WA0058.mp4…

See this output it has box like figure around the mouth region 

Please help me out if you have any idea about this

**Comment by vishal24102002** [comment]
![Screenshot_2024-10-15-23-57-05-085_com whatsapp](https://github.com/user-attachments/assets/5b22f196-0e3b-401b-8a48-fa9a798ab15c)
 This output screenshot
