### ISSUE TITLE
NO HD Video in - output_videos_hd  AFTER RUN .SH FILE

### ISSUE THREAD

**Issue by cyzzion** [saifhassan/Wav2Lip-HD#7]
After i run the final .sh command i just get all the HD Frames in the wave2liphd  Frames folder but no HD Video in the output_videos_hd folder. 

Whats the Problem?
How can i fix thad? 
Please Help 😇

**Comment by saifhassan** [comment]
> After i run the final .sh command i just get all the HD Frames in the wave2liphd Frames folder but no HD Video in the output_videos_hd folder.
> 
> Whats the Problem? How can i fix thad? Please Help 😇

uncomment the last line in `run_final.sh` and then execute again. or just go to terminal/cmd and run following command:

```
ffmpeg -r 20 -i ${back_dir}/${frames_hd}/${filename}/frame_%05d_out.jpg -i ${back_dir}/${input_audios} -vcodec libx264 -crf 25 -preset veryslow -acodec copy ${back_dir}/${output_videos_hd}/${filename}.mkv
```

variables in above command in `run_final.sh`.

Hope it works, let me know if working or any error.

**Comment by saifhassan** [comment]
I hope above solution worked for you, as for now, I'm closing this issue.

You can re-open in case of query related to this issue.

**Comment by prometheus-alien** [comment]
correct command:
`ffmpeg -r 20 -i ${back_dir}/${frames_hd}/${filename}/frame_%05d_out.jpg -i ${back_dir}/${input_audio} -vcodec libx264 -crf 25 -preset veryslow -acodec copy ${back_dir}/${output_videos_hd}/${filename}.mkv`
