### ISSUE TITLE
Teeth, vibration feeling, is there any way to solve it?

### ISSUE THREAD

**Issue by zhangsanfeng86** [saifhassan/Wav2Lip-HD#8]
Hi @saifhassan ，

Thank you for release the model.

Teeth, vibration feeling, is there any way to solve it?

https://user-images.githubusercontent.com/73547638/236983881-9dc32b6c-3cfc-48d7-a9df-1177b5da3708.mp4

**Comment by saifhassan** [comment]
> Hi @saifhassan ，
> 
> Thank you for release the model.
> 
> Teeth, vibration feeling, is there any way to solve it?
> 
>  229389414-d5cb6d33-7772-47a7-b829-9e3d5c3945a1.mp4

Thank you for raising the question, however few suggestions from my side regarding Teeth and vibration feeling.

1. Try providing hd video quality input
2. Training the model on more diverse dataset (HD quality dataset) --> Time taking

It's totally about research and hyper-parameters.

**Comment by zhangsanfeng86** [comment]
OK ，
Thanks for your quick reply!
I'll try.
